
development:
  env: 'development'
  redis_host: 'localhost'
  token_expiration_minutes: 1
  sqlite_db_name: 'database/dev.db'

test:
  env: 'test'
  redis_host: 'localhost'
  token_expiration_minutes: 10
  sqlite_db_name: 'database/test.db'

production:
  env: 'production'
  redis_host: 'localhost'
  token_expiration_minutes: 30
  sqlite_db_name: 'database/prod.db'
